[package]
name = "auth_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
tokio = { version = "1.36.0", features = ["full"] }
lazy_static = "1.4.0"
dotenv = "0.15.0"
consulrs = "=0.1.0"
