# Use official Ubuntu image
FROM ubuntu:latest

# Set working directory
WORKDIR /app

# Copy Cargo.toml and Cargo.lock for build
COPY Cargo.toml Cargo.lock ./
COPY ./src ./src
# Install Rust and Cargo
RUN apt-get update && apt-get install -y rustc cargo
RUN apt-get update && apt-get install -y libssl-dev pkg-config

# Build the Axum API in release mode
RUN cargo build --release
# Expose the port your API listens on

CMD ["cargo","run", "--release"]